name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  # cabal:
  #   name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       # os: [ubuntu-latest, macOS-latest, windows-latest]
  #       # not currently able to build mac or windows, ghc download times out
  #       os: [ubuntu-latest]
  #       cabal: ["3.2"]
  #       ghc:
  #         - "8.6.5"
  #         - "8.8.3"
  #         # known broken via servant-quickcheck
  #         # - "8.10.1"
  #       exclude:
  #         - os: macOS-latest
  #           ghc: 8.8.3
  #         - os: macOS-latest
  #           ghc: 8.6.5
  #         - os: windows-latest
  #           ghc: 8.8.3
  #         - os: windows-latest
  #           ghc: 8.6.5

    # steps:
    # - uses: actions/checkout@v2
    #   if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    # - uses: actions/setup-haskell@v1.1
    #   id: setup-haskell-cabal
    #   name: Setup Haskell
    #   with:
    #     ghc-version: ${{ matrix.ghc }}
    #     cabal-version: ${{ matrix.cabal }}

    # - uses: actions/cache@v1
    #   name: Cache cabal-store
    #   with:
    #     path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
    #     key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    # - name: Build
    #   run: |
    #     cabal update
    #     cd hstemplate
    #     cabal build all --enable-tests --enable-benchmarks --write-ghc-environment-files=always

    # - name: Test
    #   run: |
    #     cabal test all --enable-tests

  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.1.3"]
        ghc: ["8.8.3"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - name: Install HLint
      run: |
        hlint --version || stack install hlint

    - uses: actions/cache@v1
      name: Cache ~/.local/bin
      with:
        path: ~/.local/bin
        key: ${{ runner.os }}-stack

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack


    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --pedantic

    - name: Test
      run: |
        PATH=$PATH:$HOME/.local/bin stack test --system-ghc --coverage

    - name: Coverage
      run: |
        stack hpc report . --destdir hpc

    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: hpc
